server:
  port: 8088

spring:
  datasource:
    name: classroom_reservation
    url: jdbc:mysql://localhost:3306/classroom_reservation?serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true  #\u8BBE\u7F6E\u5F00\u542F\u70ED\u90E8\u7F72
      additional-paths: src/main/java #\u91CD\u542F\u76EE\u5F55
      exclude: WEB-INF/**
  freemarker:
      cache: false    #\u9875\u9762\u4E0D\u52A0\u8F7D\u7F13\u5B58\uFF0C\u4FEE\u6539\u5373\u65F6\u751F\u6548
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 891577030@qq.com #发送邮件的邮箱地址
    password:  okbpmfsfdunubeei #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 891577030@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

mybatis:
  type-aliases-package: com.cdut.classroom_reservation.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cdut.classroom_reservation: debug
